# 프라미스와 에러 핸들링

- 프라미스가 거부되면 제어 흐름이 제일 가까운 `rejection` 핸들러로 넘어가기 때문에 프라미스 체인을 사용하면 에러를 쉽게 처리할 수 있습니다. 이는 실무에서 아주 유용한 기능입니다.
- 존재하지 않는 주소를 `fetch`에 넘겨주는 예시를 살펴봅시다. `.catch`에서 에러를 처리합니다.

```js
fetch("https://no-such-server.blabla") // 거부
  .then((response) => response.json())
  .catch((err) => alert(err)); // TypeError: failed to fetch (출력되는 내용은 다를 수 있음)
```

- 예시에서 보듯 `.catch`는 첫번째 핸들러일 필요가 없고 하나 혹은 여러 개의 `.then` 뒤에 올 수 있습니다.
- 이번엔 사이트에는 아무런 문제가 없지만 응답으로 받은 `JSON`의 형식이 잘못된 경우를 살펴봅시다.
- 가장 쉬운 에러 처리 방법은 체인 끝에 `.catch`를 붙이는 것입니다.

```js
fetch("/article/promise-chaining/user.json")
  .then((response) => response.json())
  .then((user) => fetch(`https://api.github.com/users/${user.name}`))
  .then((response) => response.json())
  .then(
    (githubUser) =>
      new Promise((resolve, reject) => {
        let img = document.createElement("img");
        img.src = githubUser.avatar_url;
        img.className = "promise-avatar-example";
        document.body.append(img);

        setTimeout(() => {
          img.remove();
          resolve(githubUser);
        }, 3000);
      })
  )
  .catch((error) => alert(error.message));
```

- 정상적인 경우라면 `.catch`는 절대 트리거 되지 않습니다.
- 그런데 네트워크 문제, 잘못된 형식의 `JSON` 등으로 인해 위쪽 프라미스 중 하나라도 거부되면 `.catch`에서 에러를 잡게 됩니다.

<br>

## 암시적 try…catch

<br>

[출처]
https://ko.javascript.info/promise-error-handling
